language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - python setup.py get_question
  - pip install coveralls

before_script:
  - source stackoverflow/.travis.sh

script:
  - py.test --cov= test/

after_success:
  - coveralls
