language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - python run.py get_question

before_script:
  - source stackoverflow/.travis.sh

script:
  - cd stackoverflow/tests/
  - py.test --cov=stackoverflow tests/

after_success:
  - coveralls
