language: python
python:
  - "2.7"

install:
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls

script:
  - py.test
  - coverage report -m

after_success:
  - coveralls
