python:
  - "3.7"

install:

  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls

script:
  - py.test --cov=app

after_success:
  - coveralls
