python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
env:
  global:
    - CC_TEST_REPORTER_ID=a2a3e6dcf3fba0e0e5e1dc29e45c63413dab61df356289745179742a91755f9f

services:
  - redis-server

addons:
  postgresql: "9.6"
  # chrome: stable # Re-enable for functional tests
services:
  - postgresql

install:
  - sudo pip install requests[security]
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter

script:
  - sudo pytest --cov=app
  - sudo coverage report -m
  - flake8 tabbycat
  - coverage run tabbycat/manage.py test -v 2 --exclude-tag=selenium

after_success:
  - coverage xml
  - sudo coveralls
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
