python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install urllib3[secure] --upgrade
  - pip install -r requirements.txt
  - python setup.py develop
  - pip install coveralls

script:
  - py.test --cov=app

after_success:
  - coveralls
